{{config(materialized = 'table')}} 

WITH LOANS_DATA AS (
    SELECT
        *
    FROM
         {{source('ABRIGO_DATABASE','LOANS_DATA')}}
)

SELECT 
ENCOMPASSID, 
BLTV, 
BORROWERCOUNT, 
CHANNEL, 
CLOSINGBILLINGDATE, 
CONSTRUCTIONLOANINDICATOR, 
CREDITSCORETOUSE, 
LOANCREATEDDATEUTC, 
LOANIDNUMBER, 
LOANSOURCE, 
MATURITYDATE, 
MERSNUMBER, 
MOM, 
MORTGAGETYPE, 
OCCUPANCYTYPE, 
PMIINDICATOR, 
CORPORATEAPPROVALDATE, 
CORPORATEAPPROVEDBY, 
CURRENTLOCKDATE, 
DISCLOSURETYPE, 
LOANPROGRAM, 
PLANCODE, 
CLTV, 
DEBTTOINCOMERATIO, 
INTERESTRATE, 
LIENSTATUS, 
LOANPURPOSE, 
LOANTERM, 
LOANTYPE, 
PROPERTYTYPE, 
PROPERTYVALUE, 
STATECODE, 
TOTALLOANCOSTS, 
PROCESS_DATE, 
_FILE AS FILE_NAME,
_FIVETRAN_SYNCED
FROM
LOANS_DATA 
WHERE FILE_NAME = '/demo_loans_sftp.csv'
