dbtVersion: 1.5.1
jobs:

 - name: daily
   targetName: dev 
   schedule: 0 12 * * * 
   steps: 
     - name: run macros
       command: dbt run-operation create_apply_masking_policy
      

    
    

  
  

 
